language: php
php:
  - "7.0"
script:
- php index.php

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: practicaiclv92 <--------------------
  on:
    repo: LuisValles92/PracticaIC