language: php
php:
  - "7.0"
script:
- php index.php
deploy:
  provider: heroku
  api_key:
    secure: 0fe5256d-eb6b-43d1-857e-b1055b4450ad
  app: practicaiclv92
  on:
    repo: luisvalles92/practicaic